version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://mohan_tdo@postgres/mohantdo
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: mohan
      POSTGRES_DB: passwd
