version: "3.1"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mohan
      MONGO_INITDB_ROOT_PASSWORD: mohanpassword
    volumes:
      - mongo-database:/data/db

volumes:
  mongo-database: